-- MySQL Script generated by MySQL Workbench
-- Mon Nov 13 03:06:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mavenspacemission
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mavenspacemission` ;

-- -----------------------------------------------------
-- Schema mavenspacemission
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mavenspacemission` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mavenspacemission` ;

-- -----------------------------------------------------
-- Table `mavenspacemission`.`missions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mavenspacemission`.`missions` ;

CREATE TABLE IF NOT EXISTS `mavenspacemission`.`missions` (
  `mission_id` INT NOT NULL AUTO_INCREMENT,
  `mission` VARCHAR(255) NULL DEFAULT NULL,
  `missionstatus` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`mission_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2931
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mavenspacemission`.`launchlocations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mavenspacemission`.`launchlocations` ;

CREATE TABLE IF NOT EXISTS `mavenspacemission`.`launchlocations` (
  `launch_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`launch_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 97
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mavenspacemission`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mavenspacemission`.`companies` ;

CREATE TABLE IF NOT EXISTS `mavenspacemission`.`companies` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `company` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mavenspacemission`.`rocketinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mavenspacemission`.`rocketinfo` ;

CREATE TABLE IF NOT EXISTS `mavenspacemission`.`rocketinfo` (
  `rocket_id` INT NOT NULL AUTO_INCREMENT,
  `rocket` VARCHAR(255) NULL DEFAULT NULL,
  `rocketstatus` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`rocket_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 202
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mavenspacemission`.`space_missions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mavenspacemission`.`space_missions` ;

CREATE TABLE IF NOT EXISTS `mavenspacemission`.`space_missions` (
  `space_mission_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL DEFAULT '0',
  `launch_id` INT NOT NULL DEFAULT '0',
  `date` DATE NULL DEFAULT NULL,
  `time` TIME NULL DEFAULT NULL,
  `rocket_id` INT NOT NULL DEFAULT '0',
  `mission_id` INT NOT NULL DEFAULT '0',
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`space_mission_id`),
  INDEX `mission_details_fk_idx` (`mission_id` ASC) VISIBLE,
  INDEX `launchlocation_mission_fk_idx` (`launch_id` ASC) VISIBLE,
  INDEX `companies_incharge_fk_idx` (`company_id` ASC) VISIBLE,
  INDEX `rocket_used_in_mission_fk_idx` (`rocket_id` ASC) VISIBLE,
  CONSTRAINT `mission_details_fk`
    FOREIGN KEY (`mission_id`)
    REFERENCES `mavenspacemission`.`missions` (`mission_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `launchlocation_mission_fk`
    FOREIGN KEY (`launch_id`)
    REFERENCES `mavenspacemission`.`launchlocations` (`launch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `companies_incharge_fk`
    FOREIGN KEY (`company_id`)
    REFERENCES `mavenspacemission`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rocket_used_in_mission_fk`
    FOREIGN KEY (`rocket_id`)
    REFERENCES `mavenspacemission`.`rocketinfo` (`rocket_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2971
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
